### PR TITLE
Xmas dancer

### PR DESCRIPTION
**Pull request by Spotts9**
created a new dancer for another holiday.  Added a quick js function to check for the current month so that the button layout did not get messed up.  Halloween will show for Oct.  Christmas for Dec.

### CODE REVIEW

**Comment by lala010addict** [comment]
@Spotts9 love love the xmas dancer, i merged it! i think the logic is wrong tho. it's showing xmas dancer right now. you are welcome to open another PR to fix this. thanks!

**Comment by lala010addict** [comment]
#23 @Spotts9

**Comment by Spotts9** [comment]
@lala010addict.  Doh!   You're correct.  I switched the values to check out Christmas and then just committed.   I will open a PR to fix

**Comment by lala010addict** [comment]
thanks @Spotts9 you are awesome!

**Pull request merged**
