### PR TITLE
Give parrot a makeover so he can show off his moves

### PR DESCRIPTION
**Pull request by yongzhihuang**
Give parrot a makeover so he can show off his moves. issue #8

### CODE REVIEW

**Comment by jieyingpeng** [comment]
Awesome @yongzhihuang thanks so much!

**Comment by lala010addict** [comment]
Thanks so much! @yongzhihuang

**Comment by yongzhihuang** [comment]
@lala010addict This is a really funny project! I enjoyed it! Thanks for creating it.

**Comment by lala010addict** [comment]
@yongzhihuang thanks! your changes are deployed http://danceparty.surge.sh/ 
Feel free to make more PRs. 👍

**Comment by yongzhihuang** [comment]
@lala010addict 👍 Love all these dancers!

**Pull request merged**
